#!/bin/bash
#
# Utility for creating firmware update packages through Recovery
#
# Run: upd-maker -n <name> -d <ro.product.device> -o <update.zip> [partition images...]
#
# <title> defines the name to be displayed during the
# firmware update (service pack name).
#
# <ro.product.device> sets the name of the hardware platform for which
# designed for this package. At the moment, check the platform name
# is off, but that may change.
#
# The name of the file (without extension) with the partition image must be
# the same as the device name /dev/block/*. The only exception is
# the _aml_dtb section which is written to /dev/dtb.
#
# The image of the partition must be exactly as it is written
# to the section! In particular, the sparse ext4 images must be
# previously unpacked (e.g. with the simg2img utility)
#

NAME=
DEV=
UPD=
FILES=
CMD_START=
CMD_END=
SCRIPT=

while test -n "$1" ; do
	case $1 in
		 -n) NAME="$2"; shift ;;
		 -d) DEV="$2"; shift ;;
		 -o) UPD=$(readlink -m "$2"); shift ;;
		-cs) CMD_START="$CMD_START\n$2"; shift ;;
		-ce) CMD_END="$CMD_END\n$2"; shift ;;
		-fs) CMD_START=`cat $2`; shift ;;
		-fe) CMD_END=`cat $2`; shift ;;
		 -s) SCRIPT="$2"; shift ;;
		 -*) echo "Unknown option $1"; exit 1 ;;
		  *) break ;;
	esac
	shift
done

FILES=$*
if test -z "$UPD" ; then
	echo "Запуск: upd-maker [options] -o update.zip [partition images...]"
	echo ""
	echo "-n <name> Service pack name (displayed during installation)"
	echo "-d <d device> Target platform name (getprop ro.product.device)"
	echo "-o <update.zip> Output file"
	echo "-cs <command> Add commands to firmware"
	echo "-ce <command> Add commands after flashing"
	echo "-fs <file> Paste commands from file to firmware"
	echo "-fe <file> Paste commands from file after flashing"
	exit 1
fi

DIR=$(dirname $(readlink -f $0))
UPD_DIR="$(dirname "$UPD")/upd-maker"
UPD_SCR="$UPD_DIR/META-INF/com/google/android/updater-script"

set -e

echo "We create an update script ..."
rm -rf "$UPD_DIR"
mkdir -p "$UPD_DIR"
unzip -q "$DIR/upd-maker-template.zip" -d "$UPD_DIR"
mkdir -p "$UPD_DIR/META-INF/com/android"

if test -n "$DEV" ; then
	echo "pre-device=$DEV" >> "$UPD_DIR/META-INF/com/android/metadata"

	cat >> "$UPD_SCR" <<EOF
product=\`getprop ro.product.device\`
if test "\$product" != "$DEV" ; then
	ui_print "Package is for product $DEV, not for \$product"
	exit 1
fi
EOF
fi

test -n "$NAME" && echo "ui_print \"Installing -=<( $NAME )>=-\"" >> "$UPD_SCR"
test -n "$CMD_START" && echo -e "$CMD_START" >> "$UPD_SCR"

if test -n "$SCRIPT" ; then
	sed -e '1{' -e '/^#!/d' -e '}' "$SCRIPT" >> "$UPD_SCR"

	for x in $FILES ; do
		if ! test -e "$x" ; then
			echo "File $x does not exist" >&2
			exit 1
		fi
		file="$(basename "$x")"
		test "$UPD_DIR/$file" -ot "$x" && cp -a "$x" "$UPD_DIR/$file"
	done
else
	for x in $FILES ; do
		if ! test -e "$x" ; then
			echo "File $x does not exist" >&2
			exit 1
		fi
		file="$(basename "$x")"
		part="$(echo "$file" | sed -e 's/\..*//')"
		test "$UPD_DIR/$file" -ot "$x" && cp -a "$x" "$UPD_DIR/$file"
		case $part in
			kernel)		part=boot ;;
			DDR)		part=bootloader ;;
		esac
		dev="/dev/block/$part"
		desc="partition '$part'"
		case $part in
			bootloader)	desc=Bootloader ;;
			boot)		desc=Kernel ;;
			_aml_dtb|dtb)	dev="/dev/dtb"; desc="Device Tree" ;;
		esac
		cat >> "$UPD_SCR" <<EOF
ui_print " - Flashing $desc"
if ! package_extract_file $file $dev ; then
	ui_print "Failed to extract $file to $dev"
	exit 1
fi
EOF
	done
fi

test -n "$CMD_END" && echo -e "$CMD_END" >> "$UPD_SCR"
test -z "$SCRIPT" && echo "ui_print \"Success!\"" >> "$UPD_SCR"

echo "Creating an intermediate archive ..."
rm -f "${UPD}~"
(cd "$UPD_DIR"; zip -qr "${UPD}~" .)
rm -rf "$UPD_DIR"

echo "We sign the archive with a test key ..."
java -jar "$DIR/zipsigner-3.0.jar" "${UPD}~" "${UPD}"
rm -f "${UPD}~"

echo "Done"
